<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Brand;
use App\Models\Category;
use App\Models\Color;
use App\Models\Size;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $brands = Brand::all();
        $categories = Category::all();
        $colors = Color::all();
        $sizes = Size::all();

        $products = [
            [
                'name' => 'Nike Air Max 90',
                'description' => 'Tênis Nike Air Max 90 com tecnologia Air Max visível no calcanhar. Design clássico e confortável para uso diário.',
                'price' => 129.99,
                'sale_price' => 99.99,
                'is_sale' => true,
                'sale_ends_at' => now()->addDays(30),
                'free_shipping' => true,
                'rating' => 4.5,
                'rating_count' => 342,
                'installments' => 10,
                'installment_value' => 9.99,
                'is_new' => false,
                'image' => 'product_1.jpg',
                'brand_id' => $brands->where('name', 'Nike')->first()->id,
                'category_name' => 'Esportivo',
            ],
            [
                'name' => 'Adidas Ultraboost 22',
                'description' => 'Tênis Adidas Ultraboost 22 com tecnologia Boost para máximo conforto e performance. Ideal para corridas e treinos.',
                'price' => 189.99,
                'sale_price' => null,
                'is_sale' => false,
                'sale_ends_at' => null,
                'free_shipping' => true,
                'rating' => 4.8,
                'rating_count' => 567,
                'installments' => 12,
                'installment_value' => 15.83,
                'is_new' => true,
                'image' => 'product_2.jpg',
                'brand_id' => $brands->where('name', 'Adidas')->first()->id,
                'category_name' => 'Esportivo',
            ],
            [
                'name' => 'Puma RS-X',
                'description' => 'Tênis Puma RS-X com design retrô e estilo chunky. Perfeito para quem busca conforto e estilo urbano.',
                'price' => 89.99,
                'sale_price' => 69.99,
                'is_sale' => true,
                'sale_ends_at' => now()->addDays(15),
                'free_shipping' => true,
                'rating' => 4.3,
                'rating_count' => 234,
                'installments' => 8,
                'installment_value' => 8.75,
                'is_new' => false,
                'image' => 'product_3.jpg',
                'brand_id' => $brands->where('name', 'Puma')->first()->id,
                'category_name' => 'Casual',
            ],
            [
                'name' => 'New Balance 574',
                'description' => 'Tênis New Balance 574 clássico com tecnologia ENCAP. Conforto superior e durabilidade excepcional.',
                'price' => 119.99,
                'sale_price' => null,
                'is_sale' => false,
                'sale_ends_at' => null,
                'free_shipping' => false,
                'rating' => 4.6,
                'rating_count' => 456,
                'installments' => 10,
                'installment_value' => 11.99,
                'is_new' => true,
                'image' => 'product_4.jpg',
                'brand_id' => $brands->where('name', 'New Balance')->first()->id,
                'category_name' => 'Casual',
            ],
            [
                'name' => 'Nike Air Force 1',
                'description' => 'Tênis Nike Air Force 1 em couro branco. O clássico dos clássicos, versátil e atemporal.',
                'price' => 109.99,
                'sale_price' => 79.99,
                'is_sale' => true,
                'sale_ends_at' => now()->addDays(20),
                'free_shipping' => true,
                'rating' => 4.4,
                'rating_count' => 789,
                'installments' => 6,
                'installment_value' => 9.99,
                'is_new' => false,
                'image' => 'product_5.jpg',
                'brand_id' => $brands->where('name', 'Nike')->first()->id,
                'category_name' => 'Casual',
            ],
            [
                'name' => 'Nike Jordan',
                'description' => 'Tênis Nike Jordan com design icônico e tecnologia Air. Performance e estilo em um só produto.',
                'price' => 169.99,
                'sale_price' => null,
                'is_sale' => false,
                'sale_ends_at' => null,
                'free_shipping' => true,
                'rating' => 4.7,
                'rating_count' => 623,
                'installments' => 7,
                'installment_value' => 9.99,
                'is_new' => true,
                'image' => 'product_6.jpg',
                'brand_id' => $brands->where('name', 'Nike')->first()->id,
                'category_name' => 'Casual',
            ],
            [
                'name' => 'Asics Gel-Kayano 28',
                'description' => 'Tênis Asics Gel-Kayano 28 com tecnologia Gel para absorção de impacto. Ideal para corredores com pronação excessiva.',
                'price' => 159.99,
                'sale_price' => 129.99,
                'is_sale' => true,
                'sale_ends_at' => now()->addDays(25),
                'free_shipping' => true,
                'rating' => 4.9,
                'rating_count' => 234,
                'installments' => 12,
                'installment_value' => 10.83,
                'is_new' => false,
                'image' => 'product_7.jpg',
                'brand_id' => $brands->where('name', 'Asics')->first()->id,
                'category_name' => 'Esportivo',
            ],
            [
                'name' => 'Asics Gel-Nimbus',
                'description' => 'Tênis Asics Gel-Nimbus com tecnologia Gel para máximo conforto. Performance superior para corredores neutros.',
                'price' => 139.99,
                'sale_price' => null,
                'is_sale' => false,
                'sale_ends_at' => null,
                'free_shipping' => false,
                'rating' => 4.5,
                'rating_count' => 156,
                'installments' => 10,
                'installment_value' => 13.99,
                'is_new' => true,
                'image' => 'product_8.jpg',
                'brand_id' => $brands->where('name', 'Asics')->first()->id,
                'category_name' => 'Esportivo',
            ],
            [
                'name' => 'Fila Disruptor II',
                'description' => 'Tênis Fila Disruptor II com design chunky e estilo retrô. Perfeito para quem busca conforto e moda.',
                'price' => 89.99,
                'sale_price' => 64.99,
                'is_sale' => true,
                'sale_ends_at' => now()->addDays(10),
                'free_shipping' => true,
                'rating' => 4.2,
                'rating_count' => 198,
                'installments' => 8,
                'installment_value' => 8.12,
                'is_new' => false,
                'image' => 'product_9.jpg',
                'brand_id' => $brands->where('name', 'Fila')->first()->id,
                'category_name' => 'Casual',
            ],
            [
                'name' => 'Puma Classic',
                'description' => 'Tênis Puma Classic em couro premium. Design clássico e elegante para uso casual.',
                'price' => 99.99,
                'sale_price' => null,
                'is_sale' => false,
                'sale_ends_at' => null,
                'free_shipping' => true,
                'rating' => 4.6,
                'rating_count' => 345,
                'installments' => 9,
                'installment_value' => 11.11,
                'is_new' => true,
                'image' => 'product_10.jpg',
                'brand_id' => $brands->where('name', 'Puma')->first()->id,
                'category_name' => 'Casual',
            ],
            [
                'name' => 'Nike Zoom',
                'description' => 'Tênis Nike Zoom com tecnologia Zoom Air. Performance e conforto para atletas exigentes.',
                'price' => 179.99,
                'sale_price' => 149.99,
                'is_sale' => true,
                'sale_ends_at' => now()->addDays(35),
                'free_shipping' => true,
                'rating' => 4.4,
                'rating_count' => 123,
                'installments' => 12,
                'installment_value' => 12.50,
                'is_new' => false,
                'image' => 'product_11.jpg',
                'brand_id' => $brands->where('name', 'Nike')->first()->id,
                'category_name' => 'Esportivo',
            ],
            [
                'name' => 'Nike Air Max',
                'description' => 'Tênis Nike Air Max em couro branco. O clássico dos clássicos, versátil e atemporal.',
                'price' => 109.99,
                'sale_price' => null,
                'is_sale' => false,
                'sale_ends_at' => null,
                'free_shipping' => true,
                'rating' => 4.8,
                'rating_count' => 892,
                'installments' => 10,
                'installment_value' => 10.99,
                'is_new' => true,
                'image' => 'product_12.jpg',
                'brand_id' => $brands->where('name', 'Nike')->first()->id,
                'category_name' => 'Casual',
            ],
            [
                'name' => 'Adidas Stan Smith',
                'description' => 'Tênis Adidas Stan Smith em couro premium. Design minimalista e elegante para qualquer ocasião.',
                'price' => 89.99,
                'sale_price' => 69.99,
                'is_sale' => true,
                'sale_ends_at' => now()->addDays(18),
                'free_shipping' => true,
                'rating' => 4.7,
                'rating_count' => 567,
                'installments' => 8,
                'installment_value' => 8.75,
                'is_new' => false,
                'image' => 'product_13.jpg',
                'brand_id' => $brands->where('name', 'Adidas')->first()->id,
                'category_name' => 'Casual',
            ],
            [
                'name' => 'Puma Suede Classic',
                'description' => 'Tênis Puma Suede Classic em suede premium. Conforto e estilo em um design atemporal.',
                'price' => 79.99,
                'sale_price' => null,
                'is_sale' => false,
                'sale_ends_at' => null,
                'free_shipping' => false,
                'rating' => 4.5,
                'rating_count' => 234,
                'installments' => 7,
                'installment_value' => 11.42,
                'is_new' => true,
                'image' => 'product_14.jpg',
                'brand_id' => $brands->where('name', 'Puma')->first()->id,
                'category_name' => 'Casual',
            ],
            [
                'name' => 'New Balance 990v5',
                'description' => 'Tênis New Balance 990v5 com tecnologia ENCAP e durabilidade superior. Made in USA para qualidade excepcional.',
                'price' => 199.99,
                'sale_price' => 169.99,
                'is_sale' => true,
                'sale_ends_at' => now()->addDays(40),
                'free_shipping' => true,
                'rating' => 4.9,
                'rating_count' => 178,
                'installments' => 15,
                'installment_value' => 11.33,
                'is_new' => false,
                'image' => 'product_15.jpg',
                'brand_id' => $brands->where('name', 'New Balance')->first()->id,
                'category_name' => 'Casual',
            ],
        ];

        foreach ($products as $productData) {
            $product = Product::create([
                'name' => $productData['name'],
                'slug' => Str::slug($productData['name']),
                'description' => $productData['description'],
                'price' => $productData['price'],
                'sale_price' => $productData['sale_price'],
                'is_sale' => $productData['is_sale'],
                'sale_ends_at' => $productData['sale_ends_at'],
                'free_shipping' => $productData['free_shipping'],
                'rating' => $productData['rating'],
                'rating_count' => $productData['rating_count'],
                'installments' => $productData['installments'],
                'installment_value' => $productData['installment_value'],
                'is_new' => $productData['is_new'],
                'image' => $productData['image'],
                'brand_id' => $productData['brand_id'],
                'stock' => rand(10, 100),
            ]);

            // Adicionar categoria
            $category = $categories->where('name', $productData['category_name'])->first();
            if ($category) {
                $product->categories()->attach($category);
            }

            // Adicionar cores aleatórias
            $randomColors = $colors->random(rand(1, 3));
            $product->colors()->attach($randomColors);

            // Adicionar tamanhos aleatórios
            $randomSizes = $sizes->random(rand(3, 6));
            $product->sizes()->attach($randomSizes);
        }
    }
}
